version: "3"
services:
  frontend:
    container_name: ui
    build:
      context: ./gb-ui
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/ssl:/etc/nginx/certs